---
title: "Resume"
---

## **SUSTAINABILITY - NATURAL RESOURCES - ECOLOGY**

Emerging leader in sustainability majoring in Ecosystem Science and Sustainability with an interest in field of sustainable fashion and beauty. While in school I have been involved in the fly-fishing club and have worked in field and lab settings. I am most skilled in data analysis, written and oral communication, and time management, and my core qualities of dedication and reliability contribute to my ability to be a hard-working person. I seek to contribute my expertise in organizations focused on the future of sustainability in the world. My core competencies include:

· Adept in Microsoft Office applications, including Word, Excel, and PowerPoint

· Works well within a team and independently

· Excellent time management

· Excellent communication, both written and oral

· Works well under pressure

### **EDUCATION**

#### **Bachelor of Science in Ecosystem Science and Sustainability May 2026**

Colorado State University (CSU), Fort Collins, CO

### **PROFESSIONAL EXPERIENCE**

#### Personal Assistant November 2024-Present

· Works as part-time personal assistant to a CSU employee who is wheelchair-bound due to cerebral palsy

· Provides reliable transportation to and from weekly appointments

· Provides consistent help with weekly living tasks, including grocery shopping and laundry

· Helps maintain office organization and work-related to-do lists

· Provides transportation and other assistance as requested and as my schedule permits

#### Emmett’s Brewing Company - Host/Front of House January 2022 – January 2024

· Managed the seating chart, servers’ sections, and seating of guests in a busy bar/restaurant

· Communicated with guests about any questions or concerns

· Monitored dining room for cleanliness

· Received take-out orders with attention to detail and accuracy

### OTHER NATURAL RESOURCES EXPERIENCE

#### CSU field work class, NR220: Natural Resource Ecology & Measurements

Summer 2024, Four-week residential course on CSU’s Mountain Campus

· Conducted field research

· Took measurements for soil, rangeland identification, forestry, wildlife signs, and river flow

· Analyzed the data collected

· Gained experience in how to make wildlife/forestry management plans

### RELAVENT COURSEWORK

#### Sustainable Watershed, WR 204 Fall 2024

· Studied different ways to make water infrastructure sustainable

#### Public Communication in Natural Resources, NR 400 Fall 2024

· Gained experience in how to create ways to change people’s habits in sustainability
